AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS SG
      VpcId: !Ref MyVPC

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS DB SG
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  RDSInsatnce:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: #Your database name
      Engine: #Your Engine type
      DBSnapshotIdentifier: #Enter a name for your DB cluster
      AllocatedStorage: #The minimum value is 100 GiB and the maximum value is 65,536 GiB
      DBInstanceClass: db.t2.micro #Example
      EngineVersion: #Enter your Engine Version
      MasterUsername: #Enter your Master username
      MasterUserPassword: #Creat you password
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup