AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: # Replace with the desired CIDR block for your VPC

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
         VpcId: !Ref MyVPC
         CidrBlock: # Replace with the desired CIDR block for your VPC

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
         VpcId: !Ref MyVPC
         CidrBlock: # Replace with the desired CIDR block for your VPC

  PrivatSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
         VpcId: !Ref MyVPC
         CidrBlock: # Replace with the desired CIDR block for your VPC

  PrivatSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
         VpcId: !Ref MyVPC
         CidrBlock: # Replace with the desired CIDR block for your VPC

  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
         VpcId: !Ref MyVPC

  PublicRoute: 
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0 #For everyone
      GatewayId: !Ref MyInternetGateway
      

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
         RouteTableId: !Ref MyRouteTable
         SubnetId: !Ref PublicSubnet1
  
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
         RouteTableId: !Ref MyRouteTable
         SubnetId: !Ref PublicSubnet2

  PrivatSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
         RouteTableId: !Ref MyRouteTable
         SubnetId: !Ref PrivatSubnet1

  PrivatSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
         RouteTableId: !Ref MyRouteTable
         SubnetId: !Ref PrivatSubnet2