AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: # Replace with the desired CIDR block for your VPC
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Test
          Value: MyVPC